const CONFIG = {
  UI_SCALE: 1,
  MAX_UI_SCALE: 1.5,
  MIN_UI_SCALE: 0.5,
  IS_LEFT_PANEL_VISIBLE: true,
  IS_RIGHT_PANEL_VISIBLE: true,
  ZOOM_FACTOR_MULTIPLIER: 1.1,
} as const;

export default CONFIG;
